### ISSUE TITLE
Baseline: tool to generate Merkle tree

### ISSUE THREAD

**Issue by 0xJem** [Axis-Fi/axis-utils#4]
This is useful immediately for the Baseline integration, but we should have a script to generate a Merkle tree.

Input could be a CSV file in one of the following formats:
- address
- address,uint256 (encoded and hashed)

It spits out the merkle root, and proofs.

Can use: https://github.com/merkletreejs/merkletreejs

**Comment by Oighty** [comment]
We implemented this on the frontend in the `use-allowlist.ts` hook. After changing the contracts to use the openzeppelin format, the proper library is: https://github.com/OpenZeppelin/merkle-tree.

I'm unclear if we need a tool for this or to have them do the same kind of generation on their exchange frontend. We need to confirm with the team. I'm going to move this to "blocked".

**Comment by 0xJem** [comment]
Implemented here: https://github.com/Axis-Fi/axis-utils/tree/master/packages/oz-merkle-tree
